// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2JHRnpQqTZ0Xqp5mRzgfM58nMQbQ53LU',
    appId: '1:1057466850338:web:0a17d6b660c0cd257afe7b',
    messagingSenderId: '1057466850338',
    projectId: 'medtime-2701d',
    authDomain: 'medtime-2701d.firebaseapp.com',
    storageBucket: 'medtime-2701d.firebasestorage.app',
    measurementId: 'G-HXP7927WQF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdXozNMtbbT90RWwEYHDf2DVK9TmjYmPA',
    appId: '1:1057466850338:android:94723c5db262a9c27afe7b',
    messagingSenderId: '1057466850338',
    projectId: 'medtime-2701d',
    storageBucket: 'medtime-2701d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6Z7XkE_UpzJPMneL3aNZ1cmRIU5csYFs',
    appId: '1:1057466850338:ios:c9bbd4da878487437afe7b',
    messagingSenderId: '1057466850338',
    projectId: 'medtime-2701d',
    storageBucket: 'medtime-2701d.firebasestorage.app',
    iosClientId: '1057466850338-3e1iqe1ttcc75fl4qh11qu4mjs61hsb6.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6Z7XkE_UpzJPMneL3aNZ1cmRIU5csYFs',
    appId: '1:1057466850338:ios:c9bbd4da878487437afe7b',
    messagingSenderId: '1057466850338',
    projectId: 'medtime-2701d',
    storageBucket: 'medtime-2701d.firebasestorage.app',
    iosClientId: '1057466850338-3e1iqe1ttcc75fl4qh11qu4mjs61hsb6.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2JHRnpQqTZ0Xqp5mRzgfM58nMQbQ53LU',
    appId: '1:1057466850338:web:a02be3bee2b549207afe7b',
    messagingSenderId: '1057466850338',
    projectId: 'medtime-2701d',
    authDomain: 'medtime-2701d.firebaseapp.com',
    storageBucket: 'medtime-2701d.firebasestorage.app',
    measurementId: 'G-MW5CGJQ275',
  );
}
